version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - '27017:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  client:
    image: cazoo-challenge-frontend
    ports:
      - '80:80'

  backend:
    image: cazoo-challenge-backend
    ports:
      - '8080:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
