version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - '27017:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  client:
    image: joaofmartinho/cazoo-challenge-frontend
    ports:
      - '80:80'

  backend:
    image: joaofmartinho/cazoo-challenge-backend
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    environment:
      - DB_URI=mongodb://root:toor@mongo:27017/cazoo-database?authSource=admin&authMechanism=SCRAM-SHA-1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
